import requests
from src.config import Config
from PIL import Image as PILImage, ImageDraw, ImageFont, ImageEnhance
from io import BytesIO
from src.Utils import Utils

class Image:
    def __init__(self) -> None:
        self.config = Config()
        self.utils = Utils()
        self.image_path = "image.png"

    def getRandomImage(self):
        # Retrieve a random image from the API
        url = self.config.get("image_apiurl")
        response = requests.get(url)

        if response.status_code == 200:
            # Save the image to a file
            img = PILImage.open(BytesIO(response.content))
            img.save(self.image_path)
            return True
        else:
            return False

    def editImage(self, quote: str, author: str):
        # Load the image
        W, H = int(self.config.get("image_width")), int(self.config.get("image_height"))
        image = PILImage.open(self.image_path)

        # Adjust the brightness of the image
        bri_enhancer = ImageEnhance.Brightness(image=image)
        image = bri_enhancer.enhance(0.3)

        # Format the quote and author
        [formatted_quote, length_of_quote] = self.utils.formatTheString(
            quote=quote, author=author
        )

        # Draw the quote on the image
        image_draw = ImageDraw.Draw(image)
        fontsize = 55

        if length_of_quote <= 13:
            fontsize = 65

        image_font = ImageFont.truetype(self.config.loadfont_path("main"), fontsize)
        quote_font = ImageFont.truetype(self.config.loadfont_path(""), 15)

        _, _, w, h = image_draw.textbbox((0, 0), formatted_quote, font=image_font)
        image_draw.text(
            ((W - w) / 3, (H - h) / 2),
            formatted_quote,
            font=image_font,
            fill=(255, 255, 255, 128),
        )

        # Add information about the generator
        about_info = "Generated by, quotebot.(rasla) - Follow for more quotes."
        image_draw.text((370, 1000), about_info, font=quote_font, fill=(255, 255, 255))

        # Save the edited image
        image.save(self.image_path)

    def getRandomQuote(self):
        # Retrieve a random quote from the API
        url = self.config.get("quotable_apiurl")
        response = requests.get(url)

        if response.status_code == 200:
            # Return the quote and author as a dictionary
            return {"quote": response.json()["content"], "author": response.json()["author"]}
        else:
            # Return empty quote and author if there was an error
            return {"quote": "", "author": ""}

    def main(self):
        # Generate a random image and quote, then edit the image
        self.getRandomImage()
        quote, author = self.getRandomQuote()["quote"], self.getRandomQuote()["author"]
        self.editImage(author=author, quote=quote)
